### 1. Crear Comisión para Fútbol
POST http://localhost:8080/api/comisiones?actividadId=d851160f-f1e4-4bf7-a5de-8ddd4217e609&nombre=Turno Tarde&horario=Lunes y Miércoles 18:00&cupo=20

### 2. Listar comisiones de una actividad
GET http://localhost:8080/api/comisiones/actividad/07d936ee-4802-48b6-8fb6-7a5cf01c7ab0

### 3. Crear Comisión cupo 0
POST http://localhost:8080/api/comisiones?actividadId=b48d47a0-3f2e-481c-97c9-8f5d5c033015&nombre=Turno Mañana&horario=Lunes y Miércoles 09:00&cupo=0

### 4. Crear Comisión sin cupo
POST http://localhost:8080/api/comisiones?actividadId=b48d47a0-3f2e-481c-97c9-8f5d5c033015&nombre=Turno Medio dia&horario=Lunes y Miércoles 12:00