### 1. Inscribir Socio
POST http://localhost:8080/api/inscripciones?dni=40011019&comisionId=57c1c07e-5689-42d6-a48c-bb2e1fc22c64

### 2. Intentar inscribir socio superando el cupo
POST http://localhost:8080/api/inscripciones?dni=40011019&comisionId=d05be431-03de-4966-936a-0549039c048e

### 3. Consultar inscripciones de un socio
GET http://localhost:8080/api/inscripciones/socio/40011019